version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "5004:8080"  # Изменили здесь
    environment:
      - ASPNETCORE_URLS=http://+:8080  # Добавили для явного указания порта
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=store;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
    networks:
      - store-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: store
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Оставляем как есть
    networks:
      - store-network

volumes:
  postgres-data:

networks:
  store-network: